### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shifanakoya** [johan12345/gcs_python#12]
I am trying to install GCS_Python. But it seems it's partially installed and hence GUI is not working, could u have a look? Screenshot attached
![Screenshot from 2022-08-10 15-31-11](https://user-images.githubusercontent.com/55286796/183902048-617c7bee-bbdf-40c1-b2c9-3b792e1534a1.png)

**Comment by johan12345** [comment]
Hi! I have seen this problem before with PyQt5 on Linux, sometimes it is caused by a conflict with other installed packages (e.g. OpenCV).

Maybe you can try installing GCS in a fresh virtual environment? Or, if you're using Anaconda, you might be able to install PyQt with `conda` instead of `pip`.

**Comment by shifanakoya** [comment]
Thanks, I installed PyQt5 using conda and solved some dependency problems. but now after running the command to open GUI I get
![Screenshot from 2022-08-11 14-01-37](https://user-images.githubusercontent.com/55286796/184119667-f83f36cd-6574-407b-9371-8411bec11db7.png)
In stack it is mentioned that it is an innate problem of python 3.8 and the solution is downgrading python to 3.6, but u r GCS works only in 3.7 or > I am stuck!

**Comment by johan12345** [comment]
I think this is still a dependency incompatibility, you need to either upgrade SunPy or downgrade parfive, as mentioned here: https://github.com/sunpy/sunpy/pull/6243

**Comment by shifanakoya** [comment]
solved, sunpy 4.0.4 works!

**Comment by johan12345** [comment]
Great! 🎉
