### ISSUE TITLE
installation Issue

### ISSUE THREAD

**Issue by Shirshsoni** [johan12345/gcs_python#15]
Hi Johan,
I am trying to install the GCS package in Macbook.
after installation, i tried to run the command [gcs_gui "2020-04-15 06:00" STA SOHO]
it shows [ zsh: command not found: gcs_gui]

Could you help me out with this?
Thanks!

**Comment by johan12345** [comment]
This sounds like the directory where `pip` installs executables is not in your `PATH` environment variable (on Linux this is typically `~/.local/bin`, probably the same on Mac). `pip` probably printed a warning about this when you were installing the package.
