### ISSUE TITLE
Problem Installing GUI

### ISSUE THREAD

**Issue by NakoteyMinta** [johan12345/gcs_python#16]
I installed this GCS from the mirrored repository: https://gitlab.physik.uni-kiel.de/ET/gcs_python. which worked well. B I have changed my laptop and need to reinstall the tool again, but it is giving me an error message. Can someone help me fix the error or help me locate the mirriored repo since I cant find it again?

PS C:\Users\.......> python -m gcs.gui "2020-04-15 06:00" STA SOHO
WARNING: SunpyDeprecationWarning: The HelioviewerClient class is deprecated and may be removed in version 5.1.
        Use hvpy - https://hvpy.readthedocs.io/en/stable instead. [gcs.utils.helioviewer]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\.....\....\anaconda3\envs\gcs_CME\Lib\site-packages\gcs\gui.py", line 296, in <module>
    main()
  File "C:\......\.....\anaconda3\envs\gcs_CME\Lib\site-packages\gcs\gui.py", line 289, in main
    app = GCSGui(args.date, args.spacecraft, args.running_difference, detector_stereo=args.stereo,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.....\....\anaconda3\envs\gcs_CME\Lib\site-packages\gcs\gui.py", line 126, in __init__
    self.create_widgets()
  File "C:\.......\anaconda3\envs\gcs_CME\Lib\site-packages\gcs\gui.py", line 133, in create_widgets
    self._s_half_angle = SliderAndTextbox('Half angle, \u03B1 [°]', 0, 90, params['half_angle'])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.....\.....\anaconda3\envs\gcs_CME\Lib\site-packages\gcs\utils\widgets.py", line 16, in __init__
    self.slider.setMinimum(min / resolution)
TypeError: setMinimum(self, a0: int): argument 1 has unexpected type 'float'

**Comment by johan12345** [comment]
Hi, I no longer work at Kiel University, so I don't have access to the mirrored repository anymore. As far as I know, the gitlab.physik.uni-kiel.de instance has been shut down. But I don't think anyone there has continued working on this tool, so this repo should have the latest version.

I suspect the issue appears only with newer versions of dependencies - specifically, in this case, PyQt. The error message (at the very bottom) is quite straightforward, would you like to take a look at that place in the code and contribute a fix?

**Comment by NakoteyMinta** [comment]
Problem solved, Thanks

**Comment by Preity-bit** [comment]
> Problem solved, Thanks

Hi,
I am also getting the same error, can you please help me out how you fixed this? I am quite new to the GCS package. Thanks in advance :)
"""""
WARNING: SunpyDeprecationWarning: The HelioviewerClient class is deprecated and may be removed in version 5.1.
        Use hvpy - https://hvpy.readthedocs.io/en/stable instead. [gcs.utils.helioviewer]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/preity/anaconda3/lib/python3.11/site-packages/gcs/gui.py", line 296, in <module>
    main()
  File "/home/preity/anaconda3/lib/python3.11/site-packages/gcs/gui.py", line 289, in main
    app = GCSGui(args.date, args.spacecraft, args.running_difference, detector_stereo=args.stereo,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/preity/anaconda3/lib/python3.11/site-packages/gcs/gui.py", line 126, in __init__
    self.create_widgets()
  File "/home/preity/anaconda3/lib/python3.11/site-packages/gcs/gui.py", line 133, in create_widgets
    self._s_half_angle = SliderAndTextbox('Half angle, \u03B1 [°]', 0, 90, params['half_angle'])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/preity/anaconda3/lib/python3.11/site-packages/gcs/utils/widgets.py", line 16, in __init__
    self.slider.setMinimum(min / resolution)
TypeError: setMinimum(self, a0: int): argument 1 has unexpected type 'float'
"""

**Comment by NakoteyMinta** [comment]
Hi

Sorry for the late reply.

I found out that GCS python version is not compatible with higher versions
of python 3 ( eg. 3.11)

So I'll advise you downgrade the python version to 3.7, 3. 8 or 3.9 and try
to install the GCS tool again and problem will be resolved.

Keep me updated.

Best regards

**Comment by Preity-bit** [comment]
Hi,

Thank you for your help. It works fine now!

**Comment by NakoteyMinta** [comment]
Glad to hear it!

**Comment by Preity-bit** [comment]
Thank you again!

**Comment by johan12345** [comment]
@NakoteyMinta  @Preity-bit I have just released a new version where this issue should be fixed, also with newer versions of Python / PyQt: https://github.com/johan12345/gcs_python/commit/6419ed995ca707cd8f5c4381a4779f2ca5c58e99

**Comment by Preity-bit** [comment]
Thank you! Will try this out!
