### ISSUE TITLE
Runtime Error: OpenJPEG Version Issue when Running on Windows 11 with Anaconda

### ISSUE THREAD

**Issue by ennomuller** [johan12345/gcs_python#18]
**Description:** 

I encountered a runtime error when attempting to run the gcs_gui command as per the installation instructions provided in the README. The issue seems to stem from an outdated or improperly detected version of OpenJPEG. Below are the details of my setup, the error message, and how I resolved the issue.

---

**Steps to Reproduce:**

Install the package in a clean Anaconda Python 3.8 environment using `git+https://github.com/johan12345/gcs_python.git` as described in the README.
Run the command: `gcs_gui "2020-04-15 06:00" STA SOHO`
The error occurs during the execution of the command.
Error Message:
```
WARNING: SunpyDeprecationWarning: The HelioviewerClient class is deprecated and may be removed in version 5.1.
        Use hvpy - https://hvpy.readthedocs.io/en/stable instead. [gcs.utils.helioviewer]
Files Downloaded: 100%|████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/file]
Traceback (most recent call last):
  ...
  File "C:\Users\user\anaconda3\envs\gcs_python\lib\site-packages\glymur\jp2kr.py", line 613, in _read
    raise RuntimeError(msg)
RuntimeError: You must have a version of OpenJPEG at least as high as 2.3.0 before you can read JPEG2000 images with glymur.  Your version is 0.0.0
```

---

**Solution:**

I was able to resolve the initial runtime error by installing OpenJPEG using the following command:
`conda install -c conda-forge openjpeg`

After this, the program ran as expected. with minor errors such as the following:
```
Files Downloaded: 100%|████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.39s/file]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000015ABCC4B280>
Traceback (most recent call last):
  ...
  File "C:\Users\user\anaconda3\envs\gcs_python\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

---

**System Information:**

OS: Windows 11 23H2
Anaconda Navigator: 2.6.2
Python Version: 3.8.19

---

**Additional Information:**

The command gcs_gui -h runs without errors, just a `SunpyDeprecationWarning`.

**Comment by johan12345** [comment]
Thanks!

Yes - although this is more of an issue of SunPy or it's dependency `glymur` and not within the GCS code, I [added a hint about this in the README](https://github.com/johan12345/gcs_python/commit/c8cc9cfc40f485c3bb4a37ff86896571bcd4104f) now.
