### ISSUE TITLE
In sample_sunpy.py

### ISSUE THREAD

**Issue by MohamedNedal** [johan12345/gcs_python#4]
Hello, I got the following error at this line: 
`f = hv.download_jp2(date, observatory='STEREO_A', instrument='SECCHI', detector='COR2')`
the error: 

**File "C:\Users\DELL\anaconda3\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)

JSONDecodeError: Extra data**

How to fix it please?

**Comment by johan12345** [comment]
Hi, it seems that https://www.helioviewer.org/ is currently offline, that's probably why. You can try the mirror site https://helioviewer.ias.u-psud.fr/ by creating your HelioviewerClient in line 21 like this:
```python
hv = helioviewer.HelioviewerClient(url="https://helioviewer-api.ias.u-psud.fr/")
```

**Comment by MohamedNedal** [comment]
@johan12345  Could you please also elaborate on how to extract the CME properties from the analysis? 
The code works now, thank you!

**Comment by johan12345** [comment]
You can manually adjust the CME parameters (e.g. latitude, longitude, height, aspect ratio) in the GUI to visually fit the GCS structure to the CME in the coronagraph images from different perspectives (at least 2, better 3). When you got the structure to match in all images, then you have the CME parameters right there, there is nothing more to do to "extract" them... You can of course use multiple fits (even by different people) to check the uncertainty.

There is also some more description of the GCS model in the excerpt from my PhD thesis and the Thernisien paper, which are both linked in the README file.
