### ISSUE TITLE
GCS GUI

### ISSUE THREAD

**Issue by MohamedNedal** [johan12345/gcs_python#5]
Hello, I have a problem with running the GCS GUI. I get the following error message, Could you please attach an example code of running the GUI for some event or how can I fix this please? 

![image](https://user-images.githubusercontent.com/43330567/125037438-cfc13d80-e09c-11eb-94fa-556ab09e27bc.png)

I tried to run it inside Spyder too (python 3.7) and I got this error: 
`
gcs_gui "2020-04-15 06:00" STA SOHO
  File "<ipython-input-149-6a7cbe4ff78e>", line 1
    gcs_gui "2020-04-15 06:00" STA SOHO
                             ^
SyntaxError: invalid syntax`

**Comment by johan12345** [comment]
This is the exact same error as the one you reported in https://github.com/johan12345/gcs_python/issues/4 - so the solution is most probably the same ;)

**Comment by MohamedNedal** [comment]
@johan12345  Thank you so much! I changed the line in the main code file and it works now :)
