### ISSUE TITLE
Selecting different detectors

### ISSUE THREAD

**Issue by MohamedNedal** [johan12345/gcs_python#6]
Hello, please I would like to know how can I change the default detector? 
Currently, it shows data only from C2 detector for SOHO LASCO and COR2 for SECCHI STEREO. 
I tried the following but it didn't work: 
`gcs_gui "2017-09-6 12:48" SOHO C3`
`gcs_gui "2017-09-6 12:48" SOHO -C3`
`gcs_gui "2017-09-6 12:48" -soho {C3}`

**Comment by johan12345** [comment]
If you take a look at [the code](https://github.com/johan12345/gcs_python/blob/master/gcs/gui.py#L274-L287), you can see that the list of spacecraft to use and the telescopes to use per spacecraft are separate options, e.g.:

`gcs_gui "2017-09-06 12:48" SOHO STA -soho C3 -stereo COR2`

**Comment by MohamedNedal** [comment]
@johan12345  Thank you so much! :)
